### PR TITLE
I've added the possibility to use TLS over TCP when uri is a string (doesn't work with IP)

### PR DESCRIPTION
**Pull request by neeohw**
I've changed this to be able to use a logstash server running on Logit.io.

### CODE REVIEW

**Comment by pauldambra** [comment]
Awesome, will review this later on today. Thanks!

**Comment by pauldambra** [comment]
Looks good... If I was looking for something I'd say it'd be nice to have a `TCPSocketWriter` and a `TLSTCPSocketWriter` to avoid having to grok the conditionals but if we add a third conditional in the future that can be my signal it needs splitting.

The version needs to be bumped to 1.1.0 in the Rakefile https://github.com/pauldambra/Serilog.Sinks.Network/blob/master/rakefile.rb#L2

The assembly version files get written on build.

Once that version change is in I'm happy to merge it in. Thanks for the contribution!

**Comment by pauldambra** [comment]
I'd make those changes myself but the last time I did that Github marked me as the contributor rather than the person that opened the PR. Which seems mean!

**Comment by neeohw** [comment]
I agree on the TLSTCPSocketWriter. If I feel the need to change something to the source, I will take that up in the same time. For now I'll leave it at this

**Comment by neeohw** [comment]
I forgot to dispose of the tlsstream. This is fixed and should be ok now.

**Comment by pauldambra** [comment]
superceded by #13

**Pull request closed without merging**
